// filmstrip-view-vue-client/src/App.vue
<template>
  <div id="container">
    <header>Filmstrip View</header>
    <div id="main" role="main">
      <!-- To display corresponding thumbnail's large image and its details -->
      <ImageDetailView :template="activeTemplate" />

      <!-- To display thumbnail list -->
      <ThumbnailList
        :templates="templates"
        @onActiveTemplateChangeEvent="setActiveTemplate($event)"
        :activeTemplate="activeTemplate"
      />
    </div>
    <footer>
      <a href="instructions.pdf">Download PDF Instructions</a>
    </footer>
  </div>
</template>

<script>
import { ref } from "vue";
import { axiosCreate } from "./services/ApiService";
import ImageDetailView from "./components/ImageDetailVIew.vue";
import ThumbnailList from "./components/ThumbnailList.vue";

export default {
  name: "App",
  setup() {
    const templates = ref([]);
    const activeTemplate = ref({});

    // calls the server API to get the template data
    axiosCreate.get("/").then((response) => {
      // setting templates and active template
      templates.value = response.data;
      activeTemplate.value = response.data[0];
    });

    // set or update active template
    function setActiveTemplate(template) {
      activeTemplate.value = template;
      console.log(template);
    }

    return { templates, activeTemplate, setActiveTemplate };
  },
  components: {
    ImageDetailView,
    ThumbnailList,
  },
};
</script>

// filmstrip-view-react-client/src/App.js
import React, { useState, useEffect } from "react";
import axios from "axios";
import { BASE_URL } from "./url-config";

import Thumbnails from "./components/ThumbnailList";
import ImageDetails from "./components/ImageDetails";

import "./App.css";

function App() {
  // initialize and set templates and active template
  const [templates, setTemplates] = useState([]);
  const [activeTemplate, setActiveTemplate] = useState({});

  // get templates from api service
  const fetchTemplates = async () => {
    const res = await axios.get(BASE_URL);

    setTemplates(res.data);
    setActiveTemplate(res.data[0]);
  };

  // when component loads fetch templates
  useEffect(() => {
    fetchTemplates();
  }, []);

  return (
    <div id="container">
      <header>Filmstrip View</header>
      <div id="main" role="main">
        <ImageDetails template={activeTemplate} />

        <Thumbnails
          templates={templates}
          setActiveTemplate={setActiveTemplate}
          activeTemplate={activeTemplate}
        />
      </div>
      <footer>
        <a href="instructions.pdf">Download PDF Instructions</a>
      </footer>
    </div>
  );
}

export default App;
