// filmstrip-view-vue-client/src/components/ThumbnailList.vue
<template>
  <div class="thumbnails">
    <div class="group">
      <div v-for="template in scrollTemplates" v-bind:key="template.id">
        <a
          v-bind:href="'#'"
          v-on:click="updateTemplate(template.id, $event)"
          v-bind:class="setActive(template.id)"
          v-bind:title="template.id"
        >
          <img
            v-bind:src="thumbnailURL + template.thumbnail"
            v-bind:alt="template.id + '-m'"
            width="145"
            height="121"
          />
          <span>{{ template.id }}</span>
        </a>
      </div>
      <a
        v-on:click="movePrev()"
        v-bind:class="disablePrev"
        class="previous"
        title="Previous"
        >Previous</a
      >
      <a
        v-on:click="moveNext()"
        v-bind:class="disableNext"
        class="next"
        title="Next"
        >Next</a
      >
    </div>
  </div>
</template>

<script>
import { computed, ref } from "vue";
import { BASE_URL } from "../url-config";
export default {
  name: "ThumbnailList",
  props: ["templates", "activeTemplate"],
  emit: "onActiveTemplateChangeEvent",
  setup(props, { emit }) {
    const thumbnailURL = BASE_URL + "/assets/images/thumbnails/";
    const currentScroll = ref(0);

    // when thumbnail is clicked, change the active template
    function updateTemplate(id, e) {
      e.preventDefault();
      let template = props.templates.filter((templateItem) => {
        return templateItem.id == id;
      });

      emit("onActiveTemplateChangeEvent", template[0]);
    }

    // Highlight the active thumbnail
    function setActive(id) {
      if (props.activeTemplate.id == id) {
        return "active";
      }
    }

    // move forward the visible thumbnails by 4 positions
    function moveNext() {
      if (canMoveNext()) {
        currentScroll.value += 4;
      }
    }

    // move backward the visible thumbnails by 4 positions
    function movePrev() {
      if (canMovePrev()) {
        currentScroll.value -= 4;
      }
    }

    // check if template exists after 4 positions
    function canMoveNext() {
      if (props.templates[currentScroll.value + 4] === undefined) {
        return false;
      }
      return true;
    }

    // check if template exists before 4 positions
    function canMovePrev() {
      if (props.templates[currentScroll.value - 4] === undefined) {
        return false;
      }
      return true;
    }

    // disable prev button
    const disablePrev = computed(() => {
      if (canMovePrev() === false) {
        return "disabled";
      }
      return "";
    });

    // disable next button
    const disableNext = computed(() => {
      if (canMoveNext() === false) {
        return "disabled";
      }
      return "";
    });

    // return visible thumbnails
    const scrollTemplates = computed(() => {
      return props.templates.slice(
        Number(currentScroll.value),
        currentScroll.value + 4
      );
    });

    return {
      currentScroll,
      setActive,
      updateTemplate,
      disablePrev,
      disableNext,
      scrollTemplates,
      moveNext,
      movePrev,
      canMovePrev,
      thumbnailURL,
    };
  },
};
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

// filmstrip-view-react-client/src/components/ThumbnailList.js
import React, { useState } from "react";
import { BASE_URL } from "../url-config";
function ThumbnailList({ templates, activeTemplate, setActiveTemplate }) {
  // returns disabled for next arrow class if there are no thumbnails to show
  const thumbnailURL = BASE_URL + "images/thumbnails/";

  const [currentScroll, setCurrentScroll] = useState(0);

  // check if template exists before 4 positions
  const canMoveNext = () => {
    if (templates[currentScroll + 4] === undefined) {
      return false;
    }
    return true;
  };
  // check if template exists after 4 positions
  const canMovePrev = () => {
    if (templates[currentScroll - 4] === undefined) {
      return false;
    }
    return true;
  };

  // disable next button
  const isNextDisabled = () => {
    if (canMoveNext() === false) {
      return "disabled";
    }
  };
  // disable prev button
  const isPreviousDisabled = () => {
    if (canMovePrev() === false) {
      console.log("diabled");
      return "disabled";
    }
  };

  // move forward the visible thumbnails by 4 positions
  const moveNext = () => {
    if (canMoveNext()) {
      setCurrentScroll(currentScroll + 4);
    }
  };

  // move backward the visible thumbnails by 4 positions
  const movePrev = () => {
    if (canMovePrev()) {
      setCurrentScroll(currentScroll - 4);
    }
  };

  // return visible thumbnails
  const scrollTemplates = () => {
    return templates.slice(Number(currentScroll), currentScroll + 4);
  };

  // when thumbnail is clicked, change the active template
  const updateTemplate = (id) => {
    let template = templates.filter((templateItem) => {
      return templateItem.id === id;
    });
    setActiveTemplate(template[0]);
  };

  // Highlight the active thumbnail
  const setActive = (id) => {
    if (activeTemplate.id === id) {
      return "active";
    }
  };

  const renderedThumbnails = scrollTemplates().map((template) => {
    return (
      <a
        href="#/"
        key={template.id}
        title={template.id}
        className={setActive(template.id)}
        onClick={() => updateTemplate(template.id)}
      >
        <img
          src={thumbnailURL + template.thumbnail}
          alt="7111-m"
          width="145"
          height="121"
        />
        <span>{template.id}</span>
      </a>
    );
  });

  return (
    <div className="thumbnails">
      <div className="group">
        {renderedThumbnails}

        <span
          className={`previous ${isPreviousDisabled()}`}
          onClick={movePrev}
          title="Previous"
        >
          Previous
        </span>
        <a
          href="#/"
          className={`next ${isNextDisabled()}`}
          onClick={moveNext}
          title="Next"
        >
          Next
        </a>
      </div>
    </div>
  );
}
export default ThumbnailList;
